"""Package portable project sources, never videos, models, credentials or build products."""
import argparse
import hashlib
import json
from pathlib import Path
import tarfile

ROOT = Path(__file__).resolve().parents[1]
DIRECTORIES = ('aruco_track', 'tools', 'scripts', 'tests', 'docs', 'config', 'third_party/ORB_SLAM3')
EXCLUDE = {'.git', '__pycache__', 'build', 'build-dbow-linux', 'lib', 'Vocabulary',
           'CMakeFiles', '.DS_Store'}
EXTENSIONS = {'.py', '.html', '.js', '.mjs', '.css', '.json', '.yaml', '.yml', '.sh', '.txt',
              '.md', '.h', '.hpp', '.cc', '.cpp', '.c', '.in', '.cmake', '.glsl'}

def source_files(root=ROOT):
    selected = set()
    for path in root.iterdir():
        if path.is_file() and (path.suffix in {'.py', '.sh'} or path.name in
                              {'README.md', 'requirements.txt', 'requirements-vla.txt', '.gitignore'}):
            selected.add(path)
    for directory in DIRECTORIES:
        for path in (root/directory).rglob('*'):
            rel = path.relative_to(root)
            if (EXCLUDE.intersection(rel.parts) or any(p.startswith('build-') for p in rel.parts)
                    or path.is_symlink() or not path.is_file()):
                continue
            if path.name.endswith('.local.json'):
                continue
            if path.name == 'config.h' and 'g2o' in rel.parts:
                continue  # generated by CMake for each target platform
            if path.suffix == '.txt' and path.name != 'CMakeLists.txt' and not path.name.upper().startswith(('LICENSE', 'COPYING')):
                continue  # upstream example timestamps/IMU/ground truth are datasets, not source
            if path.suffix in EXTENSIONS or path.name.upper().startswith(('LICENSE', 'COPYING')):
                selected.add(path)
    return sorted(selected)

def manifest(root=ROOT):
    hashes = {p.relative_to(root).as_posix(): hashlib.sha256(p.read_bytes()).hexdigest()
              for p in source_files(root)}
    return dict(schema='portable-slam-release/v1', files=hashes,
                release=hashlib.sha256(json.dumps(hashes, sort_keys=True).encode()).hexdigest()[:20])

def main():
    parser=argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--output', type=Path, required=True)
    args=parser.parse_args(); args.output.mkdir(parents=True, exist_ok=True)
    data=manifest(); name=data['release']
    archive=args.output/(name+'.tar.gz'); meta=args.output/(name+'.json')
    if archive.exists() or meta.exists():
        raise FileExistsError('Release already packaged; use its existing files')
    with tarfile.open(archive,'w:gz') as tar:
        for rel in data['files']:
            tar.add(ROOT/rel, arcname=rel, recursive=False)
    data['archive_sha256']=hashlib.sha256(archive.read_bytes()).hexdigest()
    meta.write_text(json.dumps(data,indent=2)+'\n')
    print(json.dumps({'release':name,'archive':str(archive),'manifest':str(meta),'files':len(data['files'])}))

if __name__=='__main__':
    main()
